### ISSUE TITLE
App crash when selecting Primary Feed

### ISSUE THREAD

**Issue by tyrmit** [mozzius/graysky#102]
### Describe the bug

In iOS app, the app crashes when attempting to select the Primary Feed after setting Home Screen Layout to ‘A Specific Feed’

### To reproduce

1. Navigate to Settings > Home feed preferences
2. Change ‘Home screen layout’ (first option) to a specific feed (option should show ‘Primary Feed’ and have a second option underneath to set the Primary Feed)
3. Tap the Primary Feed option to select which feed, and the app crashes 

### Additional information

Issue discovered on iPhone 14 Plus running iOS 17.0.3

**Comment by mozzius** [comment]
Any chance you can tell me what feeds you have in your pinned feeds?

**Comment by tyrmit** [comment]
Screenshot (from Bluesky app):
![IMG_2578](https://github.com/mozzius/graysky/assets/37352418/f6e58891-9ca9-48cc-90a6-0ba361e4b24f)

Tried unpinning, and then deleting, each feed in turn and trying the Graysky app after each one to see if I could isolate a particular feed that might be causing the issue, but even when I got down to no feeds at all, the app was still crashing when tapping the Primary Feed setting.

**Comment by mozzius** [comment]
Ok thank you, very puzzling then. I'll investigate further

**Comment by mozzius** [comment]
If possible, please could you let me know if this still happens to you with version 1.2? I hopefully made an improvement here

**Comment by tyrmit** [comment]
Happy to report the app no longer crashes in v1.2 🙌

**Comment by mozzius** [comment]
Yay 🥳

**Comment by tumbleweed05** [comment]
I can reproduce this on iOS 17.5.1 and app version 1.5.1. I just added a ton of feeds.
