### ISSUE TITLE
Feat: Use Social Media Keyboard on iOS 

### ISSUE THREAD

**Issue by TheBreznsoiza** [mozzius/graysky#104]
### Describe the feature you'd like to request

On iOS there is the possibility use a „Social Media“ keyboard with dedicated @ und # buttons 
![IMG_5058](https://github.com/mozzius/graysky/assets/398669/7f2036c5-965f-4f21-a7f6-ea4f352f49bc)

With those dedicated buttons you can type much faster instead of searching inside the the symbols of the second layer of the keyboard 

### Describe the solution you'd like to see

Keyboard with Social Media keys on iPad and iPhone, there should be a similar solution available on Android keyboards as I remember 

### Additional information

iOS, Android

**Comment by mozzius** [comment]
Added in next version, thanks for the suggestion!
