### ISSUE TITLE
bug: Text not appearing in dark mode

### ISSUE THREAD

**Issue by pdelfan** [mozzius/graysky#108]
### Describe the bug

The colour of "That's everything!" text on feeds is not visible in dark mode.

### To reproduce

1. Visit a feed that is empty on light mode. There should be a dark text that says "That's everything!"
2. Switch to dark mode. It will disappear

### Additional information

The issue is likely due to the text not switching to a lighter colour in dark mode, so it becomes invisible in the black background.

<img width="627" alt="Screenshot 2023-10-22 at 11 54 23 AM" src="https://github.com/mozzius/graysky/assets/9456291/2fe1ceec-458c-4328-9740-f099afdaf6c2">

<img width="583" alt="Screenshot 2023-10-22 at 11 54 47 AM" src="https://github.com/mozzius/graysky/assets/9456291/ec9c7bd4-a31e-4e6d-97d2-913775c21a96">

**Comment by mozzius** [comment]
Will be fixed in the next update 👍

**Comment by Azekthi** [comment]
Got another one, this is when you try to make a post with an image without alt text with the setting to enforce alt text enabled.

![Screenshot_20231022-204207_Graysky.jpg](https://github.com/mozzius/graysky/assets/11371137/be7de441-cb6f-489d-81b7-1f56e184e97a)
