### ISSUE TITLE
feat: When viewing a profile the post button should start a post by tagging that user

### ISSUE THREAD

**Issue by blowdart** [mozzius/graysky#110]
### Describe the feature you'd like to request

When viewing a profile the post button should start a post by tagging that user

### Describe the solution you'd like to see

If I was viewing @mozzius and I hit new post the new post text should start with @mozzius.

**Comment by DayvBang** [comment]
Just a counter-opinion, I always disliked that behavior with Twitter.  If you do add this, please make it an option that can be disabled. Thanks either way for your efforts!

**Comment by mozzius** [comment]
Done
