### ISSUE TITLE
bug: User search results show results from bios [Android]

### ISSUE THREAD

**Issue by heikadog** [mozzius/graysky#114]
### Describe the bug

When you search for a user, it also seems to search for people with that query in their bios. (a simple example i ran into recently: searching "demi" brings up results from people who list themselves as demisexual in their bios instead of people just named Demi or people who have that in their username.) This can potentially introduce a lot of search results a person may not be looking for. The official Bluesky Android client does not do this.

### To reproduce

- Search for a user with a query that doesn't show up in their display name or username, but does show up in their bio
- Observe

**Comment by mozzius** [comment]
This is the Bluesky search API - not much I can do here. Annoying though :/
