### ISSUE TITLE
UI: switch x and … when viewing image in fullscreen

### ISSUE THREAD

**Issue by julez1203** [mozzius/graysky#125]
### Describe the bug

As option to go back is on the top left, so should the x when viewing an image in fullscreen

### To reproduce

- Open any image in fullscreen
- Observe current implementation (see screenshot)

### Additional information

![IMG_5305](https://github.com/mozzius/graysky/assets/147629802/2e18bc6f-f887-4034-8afc-9c963d45375d)

**Comment by mozzius** [comment]
Done in next version
