### ISSUE TITLE
feat: Set bsky.app as domain to allow easier password autofill when signing in on iOS and iPadOS

### ISSUE THREAD

**Issue by surfdude29** [mozzius/graysky#133]
### Describe the feature you'd like to request

When logging into the official app on iOS and iPadOS, the domain 'bsky.app' is "set" (not sure on correct terminology) so that password autofill requires fewer taps, as seen in this screenshot:

![IMG_9805](https://github.com/mozzius/graysky/assets/149612116/f0c02112-7c86-4a27-a3f4-5d5cf37b45d4)

On Graysky, the bsky.app domain is not set, leading to a few extra taps to autofill a password:

![IMG_9812](https://github.com/mozzius/graysky/assets/149612116/3071096a-86fe-448d-b03d-29e107bcf6cb)

### Describe the solution you'd like to see

Set the 'bsky.app' domain to speed up autofilling a password when logging in

**Comment by mozzius** [comment]
Not possible, bsky.app would need to configure their website to allow graysky to do this

**Comment by surfdude29** [comment]
Oops... sorry, I didn't realise it wasn't possible. Now that I think about it, I get why that wouldn't be allowed for security reasons.

**Comment by mozzius** [comment]
Yeah, it's a shame. Would be nice :/
