### ISSUE TITLE
feat: Add DeepL as a translation option for future premium subscribers

### ISSUE THREAD

**Issue by surfdude29** [mozzius/graysky#141]
### Describe the feature you'd like to request

When premium subscriptions are added, please add DeepL as an option for text translation. DeepL offers, in my opinion, more accurate and more natural-sounding machine translations. They claim their own tests show that their translations are preferred to Google's (although they would say that, wouldn't they...):

https://www.deepl.com/quality.html

The translation costs seem to be roughly comparable to Google, albeit slightly more, at €5/month + €20 for every million characters:

https://www.deepl.com/pro#developer

### Describe the solution you'd like to see

DeepL would be available as an option for inline text translation as well as Google

**Comment by mozzius** [comment]
I think this is a pretty good idea actually. I think I'll do it

**Comment by mozzius** [comment]
Done! Thanks for the excellent suggestion!

**Comment by surfdude29** [comment]
Thanks for adding it! 😊
