### ISSUE TITLE
feat: Add 'Translate' pop-up button to translate bio text and alt text

### ISSUE THREAD

**Issue by surfdude29** [mozzius/graysky#223]
### Describe the feature you'd like to request

When a user's bio is in a language other than the Primary language or one of My languages, it would be useful to be able to translate the bio text.

### Describe the solution you'd like to see

Adding a link such as 'Translate bio' would let the user tap the link to automatically translate the bio text.

**Comment by surfdude29** [comment]
Actually, I just had a thought: there might not be data associated with the bio text saying what language it's in? 🤔

**Comment by mozzius** [comment]
There is not, but I suppose you could guess?

**Comment by surfdude29** [comment]
I think I have a more elegant – although admittedly much less discoverable – solution than the 'Translate bio' link that I originally proposed.

When you long press the text of a post, a Copy button pops up. What if when you long press the bio text, a Translate button were to pop up?

Graysky wouldn't have to care what language(s) the bio text is in and the Translate button would always be available for the user to request a translation when needed.

**Comment by surfdude29** [comment]
This would also be useful to have for alt text
