### ISSUE TITLE
bug: Wrong Version Number on V1.2.2 Apk

### ISSUE THREAD

**Issue by WreckingBANG** [mozzius/graysky#241]
### Describe the bug

The V1.2.2 Apk has the Version Code of the V1.2.1

### To reproduce

Install V1.2.2 and look in the App Details or the About Page

**Comment by mozzius** [comment]
Hi - sorry, sounds like I might've uploaded the wrong version. I'll check it

**Comment by mozzius** [comment]
Please try again with this new version i've uploaded :)
