### ISSUE TITLE
feat: Show confirmation banner when image is successfully saved

### ISSUE THREAD

**Issue by surfdude29** [mozzius/graysky#246]
### Describe the feature you'd like to request

When you save an image from a post in the official app, you get a little confirmation banner like this to tell you that the image has been saved successfully:

![IMG_7017](https://github.com/mozzius/graysky/assets/149612116/78d595a6-e771-4e6f-80b9-e69584603c8a)

However, when you do the same thing in Graysky you don't get any confirmation that the image has been saved.

### Describe the solution you'd like to see

It would be good for Graysky to show a confirmation (maybe using the existing method of in-app notifications, like when you follow someone?) that the image has been saved successfully.

**Comment by mozzius** [comment]
Will be added in the next update

**Comment by surfdude29** [comment]
Nice, thanks man! :)

**Comment by surfdude29** [comment]
Thanks for adding this in 1.3.0! 🙏
