### ISSUE TITLE
feat: Show a preview card when tapping on a user's profile

### ISSUE THREAD

**Issue by simeonrobinson** [mozzius/graysky#259]
### Describe the feature you'd like to request

Similar to the official app, show a card with a preview of the user's profile before swiping up to show the full profile

### Describe the solution you'd like to see

Add this as a toggleable feature

**Comment by mozzius** [comment]
I don't really like this feature to be honest. Unfortunately it has a lot of knock-on effects (like clicking on someone's display name has no transition animation). Wouldn't be opposed to someone contributing it as an optional feature though
