### ISSUE TITLE
feat: Add support for linking using skeeet.xyz

### ISSUE THREAD

**Issue by justin** [mozzius/graysky#27]
### Describe the feature you'd like to request

Hey, I make [@justin/skeeet.xyz](https://github.com/justin/skeeet.xyz) which makes it easy to link to skeets that show opengraph tags in iMessage/Signal. It's currently not possible to link to a skeet using skeeet.xyz using Graysky. 

### Describe the solution you'd like to see

1. Integrate a "Share Externally" option that shares links using the site

or  

2. Change / Update how you are sharing URLs so that the existing shortcuts show up in the list of possible sharing options (this is how it works with the official Bluesky app)

### Additional information

Shortcut 1: https://www.icloud.com/shortcuts/67e784dc7843411eb02352d94151444d
Shortcut 2: https://www.icloud.com/shortcuts/e9ffec51460f4a0bb0f7e023d1323113

Both of these are linked on https://skeeet.xyz/

This is obviously a selfish request, but I use my service constantly (and make zero money off it).

**Comment by mozzius** [comment]
Hey! I’ll consider it - I had a similar mechanism using psky but removed it once bluesky moved off staging. Would be useful!

**Comment by mozzius** [comment]
What would I have to do to enable it in the share sheet? I just share the URL, unclear to me what I would be doing different to the official app there

**Comment by justin** [comment]
Since the Bluesky web app is behind an auth wall it makes it so you can share posts with other users that may not be on Bluesky.

It also makes them embed nicely if you share via iMessage or Signal like a tweet or mastodon post would. 
 
<img width="597" alt="CleanShot 2023-08-01 at 10 24 46@2x" src="https://github.com/mozzius/graysky/assets/1384/d2a65d56-c1bf-46e1-acb2-3b7f5ebc4fe2">

**Comment by mozzius** [comment]
Ah I think I figured out how the official app allows this. Will try and add sometime soon

**Comment by mozzius** [comment]
bsky.app links now have meta tags, so a solution like this is no longer needed
