### ISSUE TITLE
feat: have a feed open by default

### ISSUE THREAD

**Issue by havok89** [mozzius/graysky#29]
### Describe the feature you'd like to request

a default feed open when you hit the feeds tab. 

### Describe the solution you'd like to see

I tap feeds at the bottom of the screen then have to tap ‘following’ up at the top of the screen.
For me the main user experience is viewing my following feed (or whatever feed I’ve set as default) 

### Additional information

Maybe just requires a UX review of what is the best way to handle feeds. As it’s a social app they are the main part of it but they are now hidden behind a further tap in a different area of the screen.

**Comment by mozzius** [comment]
Thank you for this. I’m going to make changes to the layout, not entirely sure how yet but I’ll take this feedback into account

**Comment by mozzius** [comment]
Done in v0.1.5
