### ISSUE TITLE
feat: Show 'Search languages' bar by default when opening the Post Language modal

### ISSUE THREAD

**Issue by surfdude29** [mozzius/graysky#302]
### Describe the feature you'd like to request

When you open the Post Language modal you are presented with a long list of All languages which (depending on the language you want to select) might take a while to scroll through to find the option you want. There is a search bar which speeds things up considerably but this is hidden by default and the user needs to swipe down to show it, which users may not be aware of.
![IMG_2932](https://github.com/mozzius/graysky/assets/149612116/e6b0fa32-92ac-4635-832e-3e02ed175064)

### Describe the solution you'd like to see

Ideally, Graysky should show the search bar by default to make it easy to find the language you want to select.
![IMG_2933](https://github.com/mozzius/graysky/assets/149612116/4dc1a559-f880-4bc8-bd0b-0b97cc45e68e)

**Comment by mozzius** [comment]
This one is a bit of a weird iOS limitation. The OS chooses when to show it, I can't prompt it to show by default. I could alternatively pin it to the top of the screen, but it means it's visible while scrolling. would that be acceptable?

**Comment by surfdude29** [comment]
I didn't realise about the iOS limitation, that's annoying.

Pinning it to the top seems like it might work though. If the search bar is visible as soon as the user opens the modal, I would imagine most users would start typing there rather than scrolling? So it being visible while scrolling hopefully wouldn't be too much of an issue? 🤔

**Comment by mozzius** [comment]
Yeah, it's a very long list so searching is probably pretty common. Will do 👍

**Comment by surfdude29** [comment]
Nice, thanks :)
