### ISSUE TITLE
bug: No handle is shown on a repost when that user's display name is blank

### ISSUE THREAD

**Issue by surfdude29** [mozzius/graysky#394]
### Describe the bug

When a user has a blank display name and you see a repost from them, you simply see "Reposted by" and you have to tap to know who reposted that post.

Instead, please show "Reposted by [user's handle]".

### To reproduce

Make sure viewing reposts is enabled.
Follow a user who has a blank display name.
Observe that only "Reposted by" is shown when they repost something.

Here are screenshots of two occurrences I saw:

![1CBA594E-FAF8-487B-8648-AAC12498992A](https://github.com/mozzius/graysky/assets/149612116/5aaaba9d-d888-41be-aadc-4023944f49b0)

![DDA88B8F-F6DE-4316-A85F-C1F0882B296B](https://github.com/mozzius/graysky/assets/149612116/98e11491-de15-4262-99ec-d3fb768063dc)

And this is the profile of the user who reposted, showing a blank display name:

![F582164F-0C47-4166-8733-D8EABE58716D](https://github.com/mozzius/graysky/assets/149612116/44950610-6bed-4ac2-b54c-bb1c46c6a5d4)

**Comment by mozzius** [comment]
Will fix, thanks

**Comment by mozzius** [comment]
Seems they have an empty string as a handle (rather than nothing at all). I'll change the behaviour to handle that case

**Comment by surfdude29** [comment]
> Seems they have an empty string as a handle (rather than nothing at all).

I'm confused, what does it mean to have an empty string as a handle? 🤔

> I'll change the behaviour to handle that case

Brilliant, thanks! :)

**Comment by mozzius** [comment]
> > Seems they have an empty string as a handle (rather than nothing at all).
> 
> I'm confused, what does it mean to have an empty string as a handle? 🤔

Oh sorry, as a display name. I was checking if the display name was missing, rather than checking if it was blank basically (theres a difference)
