### ISSUE TITLE
French translation : Missing word 

### ISSUE THREAD

**Issue by YanYannoche** [mozzius/graysky#443]
### Describe the bug

![Screenshot_20240220_224220_Graysky](https://github.com/mozzius/graysky/assets/160554736/eb215836-a7f8-4f8a-88b7-e5b40f1e74d6)

### To reproduce

When you want to block someone, it is written "Block" instead of "Bloquer"

**Comment by mozzius** [comment]
<img width="292" alt="Screenshot 2024-02-21 at 00 51 44" src="https://github.com/mozzius/graysky/assets/10959775/83ec3847-db24-4821-8de9-90a42b97f167">
