### ISSUE TITLE
bug: `Use DeepL for translations` toggle isn't disabled in Settings > Languages

### ISSUE THREAD

**Issue by surfdude29** [mozzius/graysky#453]
### Describe the bug

A very minor thing, but the `Use DeepL for translations` toggle in Settings > Languages acts a bit weirdly if you don't have an active Pro subscription

### To reproduce

Open Settings > Languages when you don't have an active Pro subscription and observe the funky behaviour of the `Use DeepL for translations` toggle. It's not disabled, but if you try to toggle it on it quickly toggles off again.

https://github.com/mozzius/graysky/assets/149612116/c7f4a960-2bd6-4eec-bbb6-6c21c625792c

**Comment by mozzius** [comment]
Fixed in the version after next

**Comment by surfdude29** [comment]
Thanks!
