### ISSUE TITLE
feat: In landscape on an iPad open the post composer at a smaller size

### ISSUE THREAD

**Issue by surfdude29** [mozzius/graysky#454]
### Describe the feature you'd like to request

When using the app in landscape on an iPad, please open the post composer at a smaller size so that all controls are visible with the keyboard active.

### Describe the solution you'd like to see

Currently, when you open the post composer in landscape on an iPad it opens in a huge dialog/modal (not sure what the correct term is) and the keyboard hides the controls at the bottom: Add image, the language selector and the character counter, as seen in this screen recording:

https://github.com/mozzius/graysky/assets/149612116/ffd91c19-adae-4885-997f-3cd49c1764c2

Using all 300 characters of text (without line breaks) only uses up a fraction of the space given:

![IMG_1295](https://github.com/mozzius/graysky/assets/149612116/c2a32df8-82ea-439d-bf7f-d17c0816bce6)

So if it's possible, could you please set the post composer to open up at a smaller size in this scenario 🙏

**Comment by mozzius** [comment]
Not possible, sorry :/

**Comment by surfdude29** [comment]
Ah that's a shame
