### ISSUE TITLE
feat: Visual Studio App Center

### ISSUE THREAD

**Issue by reindex-ot** [mozzius/graysky#462]
### Describe the feature you'd like to request

Distribution of test builds using Visual Studio App Center.

### Describe the solution you'd like to see

How about including crash report reporting and test build delivery using Visual Studio App Center?
https://azure.microsoft.com/en-gb/products/app-center/

**Comment by mozzius** [comment]
Thanks for the suggestion, but I'm pretty happy with the current workflow
