### ISSUE TITLE
feat: offer the option to use more a contemporary BlueSky artstyle 

### ISSUE THREAD

**Issue by hiya-tiger** [mozzius/graysky#518]
### Describe the feature you'd like to request

GraySky looks like BlueSky before the recent rebrand. Give us the option to switch the a modern style.

### Describe the solution you'd like to see

![IMG_5753](https://github.com/user-attachments/assets/feec8ce0-4462-480f-8d94-7409aac21d14)
![IMG_5743](https://github.com/user-attachments/assets/49c2e875-26fb-465d-a698-4b8c7b1c317d)

These, like almost exactly.

**Comment by mozzius** [comment]
I can't use the Bluesky logo, that's copyrighted
