### ISSUE TITLE
feat: Feedback on successful post

### ISSUE THREAD

**Issue by barneycarroll** [mozzius/graysky#57]
### Describe the feature you'd like to request

There isn’t any formal feedback for a successful sui-generis post from main; the ‘post’ button shows a spinner until resolution but upon resolution, there is no confirmation message, and unless the current view refreshing would incidentally reveal the post in context as an incidental secondary effect, it will not be visible.

### Describe the solution you'd like to see

Navigate to the post view on success.

**Comment by mozzius** [comment]
It refreshes the current view on post send, it's not a coincidence. However, you're right, and I should add this 👍

**Comment by mozzius** [comment]
Done in v0.1.5
