### ISSUE TITLE
bug: Refreshed post context views after successfully deleting a post still display the deleted post

### ISSUE THREAD

**Issue by barneycarroll** [mozzius/graysky#58]
### Describe the bug

Deleting a post from a view context focused on that post always results in a confusing stake view which still shows that post.

### To reproduce

1. Navigate to own post
2. Delete the post
3. Acknowledge post deletion confirmation modal
4. Wait for bottom-of-thread spinner to disappear
5. Post remains visible
6. Deleting any subsequent threaded posts will not cause them to disappear either
7. Attempting to delete the posts again yields same confirmation modals 
8. Navigating away (eg to profile from post meta UI) then returning via backwards context navigation persists the stale data view

# Suggestion

Upon successful deletion, navigate back to previous context (and refresh view as normal)

**Comment by mozzius** [comment]
I think this is done
