### ISSUE TITLE
bug: As of 0.1.5, search is no longer visible [Android alpha]

### ISSUE THREAD

**Issue by heikadog** [mozzius/graysky#60]
### Describe the bug

There's no way to search anything currently. The tab is there, shows suggested follows, and is labeled Search at the top, but there's no search.

### To reproduce

1. Check the Search tab
2. Observe

### Additional information

On a Pixel 4a 5G, Android 13.
![Screenshot_20230927-025800](https://github.com/mozzius/graysky/assets/41552394/39378299-0e98-4678-a911-3dd99442b123)

**Comment by mozzius** [comment]
will be fixed with version 1.0.0
