### ISSUE TITLE
feat: hosting apks on github

### ISSUE THREAD

**Issue by 99kaits** [mozzius/graysky#62]
### Describe the feature you'd like to request

The beta test thing doesn't work on Aurora Store and other third party play store clients. Honestly it'd just be nice to be able to download the app without using Google

### Describe the solution you'd like to see

apk builds and release tags on github would probably be the way to go

### Additional information

My phone runs a degoogled rom and I don't currently have a computer capable of building android apps so I ended up having to sideload a googled rom in DSU and extract the apk from that to get the app on my phone. All the process did is remind me why i run degoogled. I probably will not be updating the app now unless aurora somehow manages to update it because it was painful enough just to get it.

**Comment by mozzius** [comment]
Done!

https://github.com/mozzius/graysky/releases/tag/v0.1.5-beta
