### ISSUE TITLE
feat: support for multiple accounts

### ISSUE THREAD

**Issue by jeremymanning** [mozzius/graysky#73]
### Describe the feature you'd like to request

I'd love to see support for multiply bluesky accounts.  For example, I have one "personal" account along with a "work" account for my research group.  It'd be nice to be able to manage both from within a single app.

### Describe the solution you'd like to see

My preference would be:
  - Press on your profile picture (circle in the top left) to open up the preferences/setting menu
  - Add the following items to that menu:
    - An option to "Add an account"
    - If other accounts are available, an option to switch to another account whose credentials have been stored in the app

### Additional information

The "default" bluesky app has a somewhat inconvenient and glitchy way of handling multiple accounts:
  - Open "settings/preferences" hamburger menu
  - Click "settings"
  - Slick desired account under a "signed in as" menu
  - Wait a beat for the app to "reload" or "refresh" and populate itself with the new account

It'd be nice to be able to more quickly and smoothly flip between multiple accounts (fewer presses + smoother behavior) in Graysky.

By the way, thanks for developing this excellent app-- it's fantastic and I'm excited about its future!!

**Comment by mozzius** [comment]
Already done it actually! It'll be released when the app launches on the 21st October

(p.s. in the official app, you can long press your profile picture in the bottom tab bar to quick switch accounts - I added this feature to the official app myself 😅)

**Comment by jeremymanning** [comment]
very cool, looking forward to the official release!  thanks for the update!
