### ISSUE TITLE
Silly yellow and blue bar on android

### ISSUE THREAD

**Issue by LukaTV939** [mozzius/graysky#74]
### Describe the bug

I guess it's a pop-up saying that you post a skeet or deleted one, but it's not that well implemented 

### To reproduce

Here are some clips

https://github.com/mozzius/graysky/assets/55237683/4e33eae6-bc5e-4ef4-ac0d-5489b7758108

https://github.com/mozzius/graysky/assets/55237683/d531a447-5518-4604-bd1b-aecfecbbe6b7

### Additional information

Not related to this specific issue but Idk if posting gifs is out yet. I tried posting a gif (in the second video) and it's just an image

**Comment by mozzius** [comment]
Fixed in next update, sorry about that
