### ISSUE TITLE
Line break inside initial splash screen

### ISSUE THREAD

**Issue by emkadoc** [mozzius/graysky#93]
### Describe the bug

Size of the text 'Graysky' seems not dynamically resizing depending on different screen sizes.
E.g. the letter 'y' breaks and falls into the next line (see screenshot).

#### 1st possibility (before first usage)

1. Download App
2. Open App

#### 2nd possibility (already in usage)

1. Just logout

#### Test-Environment
- Device: iPhone XS
- OS: iOS 17.0.3
- Display/Screen: 2436 x 1125 Pixel

### Screenshot
![image](https://github.com/mozzius/graysky/assets/78759871/4ab54e58-8b0a-4018-aa22-4f2075a5d844)

**Comment by mozzius** [comment]
lol I did not do enough testing on small phones, clearly! Will fix
