### ISSUE TITLE
feat: remove account 

### ISSUE THREAD

**Issue by gufertum** [mozzius/graysky#97]
### Describe the feature you'd like to request

Currently you can not remove an existing account from the account list.

### Describe the solution you'd like to see

Remove an existing account.

**Comment by kjarex** [comment]
Just as a note for when the feature gets added and tested: I had sometimes (maybe every 5 accounts out of 20?) a lot of issues deleting accounts (with the pds claiming the code was incorrect). So if you run into this issue while testing, it might be not your fault ("workaround":  try it just every day and it should work within about 10 days eventually; problem was reported to bsky repeatedly from March to October, but never heard back from them)

**Comment by mozzius** [comment]
> Just as a note for when the feature gets added and tested: I had sometimes (maybe 5 accounts out of 20?) a lot of issues deleting accounts (with the pds claiming the code was incorrect). So if you run into this issue while testing, it might be not your fault ("workaround":  try it just every day and it should work within about 10 days eventually; problem was reported to bsky repeatedly from March to October, but never heard back from them)

I this is issue is regarding removing accounts from the quick switch? But good to know, thank you

**Comment by mozzius** [comment]
Done in next version
