### ISSUE TITLE
feat: Fast account switch

### ISSUE THREAD

**Issue by gufertum** [mozzius/graysky#98]
### Describe the feature you'd like to request

Currently you need 4 clicks to switch an account.
- long click in the top left image
- sign out
- Log in
- Choose account 

### Describe the solution you'd like to see

Directly choose the account after the click on the profile picture

**Comment by mozzius** [comment]
Long press the profile tab, like the official app

**Comment by gufertum** [comment]
👍 thanks, i was too dumb 🤦
