### ISSUE TITLE
Cut a release for launch

### ISSUE THREAD

**Issue by Emiller88** [mozzius/graysky#99]
### Describe the feature you'd like to request

Hey, I'm using [obtainium](https://github.com/ImranR98/Obtainium) to install graysky, so it only updates whenever a release with an apk is uploaded to GitHub.

### Describe the solution you'd like to see

Versions on Google play staying in sync with this releases on this repo.

**Comment by mozzius** [comment]
Done!

https://github.com/mozzius/graysky/releases/tag/v1.0.1
